import {
  AppBar,
  Box,
  Card,
  CardContent,
  CardMedia,
  Fab,
  IconButton,
  Toolbar,
  Typography,
} from '@mui/material'
import Icon from '@mui/material/Icon'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Router from 'next/router'
import { useCallback } from 'react'

function PlaylistCard() {
  return (
    <Card sx={{ display: 'flex' }} onClick={() => Router.push('/test')}>
      <CardMedia
        component="img"
        sx={{ width: 151 }}
        image="https://mui.com/static/images/cards/live-from-space.jpg"
        alt="Live from space album cover"
      />
      <Box sx={{ display: 'flex', flexDirection: 'column' }}>
        <CardContent sx={{ flex: '1 0 auto' }}>
          <Typography component="div" variant="h6">
            JunkBox Playlist
          </Typography>
          <Typography
            variant="subtitle1"
            color="text.secondary"
            component="div"
          >
            Mac Miller
          </Typography>
        </CardContent>
        <Box sx={{ display: 'flex', alignItems: 'center', pl: 2, pb: 1 }}>
          <Typography>items: 2</Typography>
        </Box>
      </Box>
    </Card>
  )
}

const Home: NextPage = () => {
  const handleOnClickFab = useCallback(() => Router.push('/new-playlist'), [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="fixed">
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
          >
            <Icon>menu</Icon>
          </IconButton>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Playlists
          </Typography>
          {/* <IconButton color="inherit">
            <Icon>person</Icon>
          </IconButton> */}
        </Toolbar>
      </AppBar>

      <Box
        sx={{
          display: 'flex',
          mt: 9,
          flexDirection: 'column',
          rowGap: 1,
        }}
      >
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
        <PlaylistCard />
      </Box>

      <Fab
        color="primary"
        aria-label="add"
        sx={{ position: 'fixed', bottom: 36, right: 20 }}
        onClick={handleOnClickFab}
      >
        <Icon>add</Icon>
      </Fab>

      <Link href="/login">login</Link>
    </>
  )
}

export default Home
