import {
  AppBar,
  Box,
  Card,
  CardContent,
  CardMedia,
  CircularProgress,
  Fab,
  IconButton,
  Toolbar,
  Typography,
} from '@mui/material'
import Icon from '@mui/material/Icon'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Router from 'next/router'
import { useCallback } from 'react'
import usePlaylists from '@/hooks/dataHooks/usePlaylists'

function PlaylistCard({ playlist }: any) {
  return (
    <Card
      sx={{ display: 'flex' }}
      onClick={() => Router.push(`/${playlist.id}`)}
    >
      <CardMedia
        component="img"
        sx={{ width: 151 }}
        image="https://mui.com/static/images/cards/live-from-space.jpg"
        alt="Live from space album cover"
      />
      <Box sx={{ display: 'flex', flexDirection: 'column', width: '100%' }}>
        <CardContent sx={{ flex: '1 0 auto' }}>
          <Typography component="div" variant="h6">
            {playlist.name}
          </Typography>
          <Typography
            variant="subtitle1"
            color="text.secondary"
            component="div"
          >
            {playlist?.user?.name || 'Mac'}
          </Typography>
        </CardContent>
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            px: 2,
            pb: 1,
          }}
        >
          <Typography>Items: {playlist.tracksCount}</Typography>
        </Box>
      </Box>
    </Card>
  )
}

const Home: NextPage = () => {
  const [playlists, loading, error] = usePlaylists()

  const handleOnClickFab = useCallback(() => Router.push('/new-playlist'), [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="fixed">
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
          >
            <Icon>menu</Icon>
          </IconButton>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Playlists
          </Typography>
          {/* <IconButton color="inherit">
            <Icon>person</Icon>
          </IconButton> */}
          <Link href="/login">login</Link>
        </Toolbar>
      </AppBar>
      <Box
        sx={{
          display: 'flex',
          mt: 8,
          flexDirection: 'column',
          rowGap: 1,
          pt: { lg: 2 },
          pb: 10,
          maxWidth: '28rem',
          marginInline: 'auto',
        }}
      >
        {loading || error ? (
          <Box sx={{ display: 'flex', justifyContent: 'center', pt: 5 }}>
            <CircularProgress />
          </Box>
        ) : (
          <>
            {playlists.map((playlist: any) => (
              <PlaylistCard playlist={playlist} />
            ))}
          </>
        )}
      </Box>
      <Fab
        color="primary"
        aria-label="add"
        sx={{ position: 'fixed', bottom: 65, right: 20 }}
        onClick={handleOnClickFab}
      >
        <Icon>add</Icon>
      </Fab>
    </>
  )
}

export default Home
